plugins {
    id("fabric-loom") version("${fabric_loom_version}") apply(false)
    id("net.minecraftforge.gradle") version("${forge_gradle_version}") apply(false)
    id("org.spongepowered.gradle.vanilla") version("${spongepowered_gradle_version}") apply(false)
    id("org.spongepowered.mixin") version("${mixin_plugin_version}") apply(false)
    id("me.modmuss50.mod-publish-plugin") version("${publisher_plugin_version}") apply(false)
}

subprojects {
    apply plugin: "java"
    apply plugin: "maven-publish"
    apply plugin: "idea"

    java.toolchain.languageVersion = JavaLanguageVersion.of(17)
    java.withSourcesJar()
    java.withJavadocJar()

    jar {
        from(rootProject.file("LICENSE")) {
            rename { "${it}_${mod_name}" }
        }

        manifest {
            attributes([
                    'Specification-Title'     : mod_name,
                    'Specification-Vendor'    : mod_credits,
                    'Specification-Version'   : mod_version,
                    'Implementation-Title'    : mod_name,
                    'Implementation-Version'  : mod_version,
                    'Implementation-Vendor'   : mod_credits,
                    'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                    'Timestamp'               : System.currentTimeMillis(),
                    'Built-On-Java'           : "${System.getProperty('java.vm.version')} (${System.getProperty('java.vm.vendor')})",
                    'Built-On-Minecraft'      : minecraft_version
            ])
        }
    }

    sourcesJar {
        from(rootProject.file("LICENSE")) {
            rename { "${it}_${mod_name}" }
        }
    }

    repositories {
        mavenCentral()

        maven {
            name = "Spongepowered Maven"
            url = "https://repo.spongepowered.org/repository/maven-public/"
        }

        maven {
            name = "CurseMaven"
            url = "https://www.cursemaven.com"
        }

        maven {
            name = "Modrinth"
            url = "https://api.modrinth.com/maven"
        }

        maven {
            name = "BlameJared maven"
            url = "https://maven.blamejared.com/"
        }

        maven {
            name = "RyanLiptak Maven"
            url = "https://maven.ryanliptak.com/"
        }

        maven {
            name = "TerraformersMC Maven"
            url = "https://maven.terraformersmc.com/releases"
        }

        maven {
            name = "CubicInterpolation Maven"
            url = "https://cubicinterpolation.net/maven/"
        }
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.encoding = 'UTF-8'
        it.options.getRelease().set(17)
    }

    tasks.withType(Javadoc).configureEach {
        it.options.encoding = 'UTF-8'
        it.options.addStringOption('Xdoclint', 'none')
        it.failOnError = false
    }

    processResources {
        def props = new Properties()

        rootProject.file('gradle.properties').withInputStream { props.load(it) }

        // Filter out any non-String values and system properties
        def replaceProperties = [:]

        props.each { key, value ->
            if (value instanceof String) {
                replaceProperties.put(key, value)
            }
        }

        inputs.properties(replaceProperties)
        filesMatching(['META-INF/mods.toml', 'fabric.mod.json', 'pack.mcmeta', '*.mixins.json']) {
            expand replaceProperties + [project: project]
        }
    }

    tasks.withType(GenerateModuleMetadata).configureEach {
        enabled = false
    }

    publishing {
        repositories {
            maven {
                name = ""
                url = ""

                credentials {
                }
            }
        }
    }
}
