package io.github.chaosawakens.client.animation.baked.neutral.rubber_ducky;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

public class RubberDuckyAnimation {
    public static final AnimationDefinition WATER_IDLE = AnimationDefinition.Builder.withLength(4.0F).looping()
            .addAnimation("Rubber_ducky", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 3.0F, -3.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.16F, KeyframeAnimations.degreeVec(-1.45F, 2.91F, -2.91F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.28F, KeyframeAnimations.degreeVec(-2.31F, 2.71F, -2.71F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.4F, KeyframeAnimations.degreeVec(-2.85F, 2.43F, -2.43F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.52F, KeyframeAnimations.degreeVec(-2.99F, 2.05F, -2.05F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.64F, KeyframeAnimations.degreeVec(-2.71F, 1.61F, -1.61F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.76F, KeyframeAnimations.degreeVec(-2.05F, 1.1F, -1.1F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.92F, KeyframeAnimations.degreeVec(-0.75F, 0.38F, -0.38F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.16F, KeyframeAnimations.degreeVec(1.45F, -0.75F, 0.75F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.28F, KeyframeAnimations.degreeVec(2.31F, -1.28F, 1.28F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.4F, KeyframeAnimations.degreeVec(2.85F, -1.76F, 1.76F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.52F, KeyframeAnimations.degreeVec(2.99F, -2.19F, 2.19F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.64F, KeyframeAnimations.degreeVec(2.71F, -2.53F, 2.53F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.76F, KeyframeAnimations.degreeVec(2.05F, -2.79F, 2.79F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.92F, KeyframeAnimations.degreeVec(0.75F, -2.98F, 2.98F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.12F, KeyframeAnimations.degreeVec(-1.1F, -2.95F, 2.95F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.28F, KeyframeAnimations.degreeVec(-2.31F, -2.71F, 2.71F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.4F, KeyframeAnimations.degreeVec(-2.85F, -2.43F, 2.43F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.52F, KeyframeAnimations.degreeVec(-2.99F, -2.05F, 2.05F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.64F, KeyframeAnimations.degreeVec(-2.71F, -1.61F, 1.61F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.76F, KeyframeAnimations.degreeVec(-2.05F, -1.1F, 1.1F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.92F, KeyframeAnimations.degreeVec(-0.75F, -0.38F, 0.38F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(3.16F, KeyframeAnimations.degreeVec(1.45F, 0.75F, -0.75F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(3.28F, KeyframeAnimations.degreeVec(2.31F, 1.28F, -1.28F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(3.4F, KeyframeAnimations.degreeVec(2.85F, 1.76F, -1.76F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(3.52F, KeyframeAnimations.degreeVec(2.99F, 2.19F, -2.19F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(3.64F, KeyframeAnimations.degreeVec(2.71F, 2.53F, -2.53F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(3.76F, KeyframeAnimations.degreeVec(2.05F, 2.79F, -2.79F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(3.92F, KeyframeAnimations.degreeVec(0.75F, 2.98F, -2.98F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(4.0F, KeyframeAnimations.degreeVec(0.0F, 3.0F, -3.0F), AnimationChannel.Interpolations.LINEAR)
            ))
            .addAnimation("Rubber_ducky", new AnimationChannel(AnimationChannel.Targets.POSITION,
                    new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -0.8F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.04F, KeyframeAnimations.posVec(0.02F, -0.8F, 0.03F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.16F, KeyframeAnimations.posVec(0.07F, -0.86F, 0.1F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.32F, KeyframeAnimations.posVec(0.14F, -1.03F, 0.17F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.52F, KeyframeAnimations.posVec(0.22F, -1.33F, 0.2F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.68F, KeyframeAnimations.posVec(0.26F, -1.57F, 0.17F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.84F, KeyframeAnimations.posVec(0.29F, -1.74F, 0.1F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.96F, KeyframeAnimations.posVec(0.3F, -1.8F, 0.03F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.04F, KeyframeAnimations.posVec(0.3F, -1.8F, -0.03F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.16F, KeyframeAnimations.posVec(0.29F, -1.74F, -0.1F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.32F, KeyframeAnimations.posVec(0.26F, -1.57F, -0.17F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.52F, KeyframeAnimations.posVec(0.21F, -1.27F, -0.2F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.68F, KeyframeAnimations.posVec(0.14F, -1.03F, -0.17F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.84F, KeyframeAnimations.posVec(0.07F, -0.86F, -0.1F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.96F, KeyframeAnimations.posVec(0.02F, -0.8F, -0.03F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.04F, KeyframeAnimations.posVec(-0.02F, -0.8F, 0.03F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.16F, KeyframeAnimations.posVec(-0.07F, -0.86F, 0.1F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.32F, KeyframeAnimations.posVec(-0.14F, -1.03F, 0.17F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.52F, KeyframeAnimations.posVec(-0.22F, -1.33F, 0.2F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.68F, KeyframeAnimations.posVec(-0.26F, -1.57F, 0.17F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.84F, KeyframeAnimations.posVec(-0.29F, -1.74F, 0.1F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.96F, KeyframeAnimations.posVec(-0.3F, -1.8F, 0.03F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(3.04F, KeyframeAnimations.posVec(-0.3F, -1.8F, -0.03F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(3.16F, KeyframeAnimations.posVec(-0.29F, -1.74F, -0.1F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(3.32F, KeyframeAnimations.posVec(-0.26F, -1.57F, -0.17F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(3.52F, KeyframeAnimations.posVec(-0.21F, -1.27F, -0.2F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(3.68F, KeyframeAnimations.posVec(-0.14F, -1.03F, -0.17F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(3.84F, KeyframeAnimations.posVec(-0.07F, -0.86F, -0.1F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(3.96F, KeyframeAnimations.posVec(-0.02F, -0.8F, -0.03F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(4.0F, KeyframeAnimations.posVec(0.0F, -0.8F, 0.0F), AnimationChannel.Interpolations.LINEAR)
            ))
            .addAnimation("Rubber_ducky", new AnimationChannel(AnimationChannel.Targets.SCALE,
                    new Keyframe(0.0F, KeyframeAnimations.scaleVec(0.9875F, 0.9567F, 0.9875F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.24F, KeyframeAnimations.scaleVec(1.0057F, 0.9513F, 1.0057F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.52F, KeyframeAnimations.scaleVec(1.0224F, 0.9778F, 1.0224F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.84F, KeyframeAnimations.scaleVec(1.0214F, 1.0259F, 1.0214F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.08F, KeyframeAnimations.scaleVec(1.0067F, 1.0482F, 1.0067F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.32F, KeyframeAnimations.scaleVec(0.9884F, 1.0443F, 0.9884F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.68F, KeyframeAnimations.scaleVec(0.975F, 0.9979F, 0.975F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.0F, KeyframeAnimations.scaleVec(0.9875F, 0.9567F, 0.9875F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.24F, KeyframeAnimations.scaleVec(1.0057F, 0.9513F, 1.0057F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.52F, KeyframeAnimations.scaleVec(1.0224F, 0.9778F, 1.0224F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.84F, KeyframeAnimations.scaleVec(1.0214F, 1.0259F, 1.0214F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(3.08F, KeyframeAnimations.scaleVec(1.0067F, 1.0482F, 1.0067F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(3.32F, KeyframeAnimations.scaleVec(0.9884F, 1.0443F, 0.9884F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(3.68F, KeyframeAnimations.scaleVec(0.975F, 0.9979F, 0.975F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(4.0F, KeyframeAnimations.scaleVec(0.9875F, 0.9567F, 0.9875F), AnimationChannel.Interpolations.LINEAR)
            ))
            .addAnimation("Left_tendril_eye", new AnimationChannel(AnimationChannel.Targets.SCALE,
                    new Keyframe(0.0F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
            ))
            .addAnimation("Left_tendril", new AnimationChannel(AnimationChannel.Targets.SCALE,
                    new Keyframe(0.0F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
            ))
            .addAnimation("Left_tendril2", new AnimationChannel(AnimationChannel.Targets.SCALE,
                    new Keyframe(0.0F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
            ))
            .addAnimation("Right_tendril2", new AnimationChannel(AnimationChannel.Targets.SCALE,
                    new Keyframe(0.0F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
            ))
            .addAnimation("Right_tendril", new AnimationChannel(AnimationChannel.Targets.SCALE,
                    new Keyframe(0.0F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
            ))
            .addAnimation("tail", new AnimationChannel(AnimationChannel.Targets.SCALE,
                    new Keyframe(0.0F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
            ))
            .addAnimation("Right_tendril_eye", new AnimationChannel(AnimationChannel.Targets.SCALE,
                    new Keyframe(0.0F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
            ))
            .build();

    public static final AnimationDefinition BOUNCE = AnimationDefinition.Builder.withLength(0.88F).looping()
            .addAnimation("Left_tendril_eye", new AnimationChannel(AnimationChannel.Targets.SCALE,
                    new Keyframe(0.0F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
            ))
            .addAnimation("Left_tendril", new AnimationChannel(AnimationChannel.Targets.SCALE,
                    new Keyframe(0.0F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
            ))
            .addAnimation("Left_tendril2", new AnimationChannel(AnimationChannel.Targets.SCALE,
                    new Keyframe(0.0F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
            ))
            .addAnimation("Right_tendril2", new AnimationChannel(AnimationChannel.Targets.SCALE,
                    new Keyframe(0.0F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
            ))
            .addAnimation("Right_tendril", new AnimationChannel(AnimationChannel.Targets.SCALE,
                    new Keyframe(0.0F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
            ))
            .addAnimation("tail", new AnimationChannel(AnimationChannel.Targets.SCALE,
                    new Keyframe(0.0F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
            ))
            .addAnimation("Right_tendril_eye", new AnimationChannel(AnimationChannel.Targets.SCALE,
                    new Keyframe(0.0F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
            ))
            .addAnimation("Root", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0.0F, KeyframeAnimations.degreeVec(-8.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.04F, KeyframeAnimations.degreeVec(-3.87F, 0.0F, 5.2F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.08F, KeyframeAnimations.degreeVec(0.56F, 0.0F, 6.96F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.12F, KeyframeAnimations.degreeVec(4.94F, 0.0F, 4.11F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.16F, KeyframeAnimations.degreeVec(8.95F, 0.0F, -1.46F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.2F, KeyframeAnimations.degreeVec(12.26F, 0.0F, -6.06F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.24F, KeyframeAnimations.degreeVec(14.62F, 0.0F, -6.66F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.28F, KeyframeAnimations.degreeVec(15.84F, 0.0F, -2.85F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.32F, KeyframeAnimations.degreeVec(15.84F, 0.0F, 2.85F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.36F, KeyframeAnimations.degreeVec(14.62F, 0.0F, 6.66F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.4F, KeyframeAnimations.degreeVec(12.26F, 0.0F, 6.06F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.44F, KeyframeAnimations.degreeVec(8.95F, 0.0F, 1.46F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.48F, KeyframeAnimations.degreeVec(4.94F, 0.0F, -4.11F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.52F, KeyframeAnimations.degreeVec(0.56F, 0.0F, -6.96F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.56F, KeyframeAnimations.degreeVec(-3.87F, 0.0F, -5.2F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.6F, KeyframeAnimations.degreeVec(-8.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.64F, KeyframeAnimations.degreeVec(-11.51F, 0.0F, 5.2F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.68F, KeyframeAnimations.degreeVec(-14.13F, 0.0F, 6.96F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.72F, KeyframeAnimations.degreeVec(-15.65F, 0.0F, 4.11F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.76F, KeyframeAnimations.degreeVec(-15.96F, 0.0F, -1.46F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.8F, KeyframeAnimations.degreeVec(-15.04F, 0.0F, -6.06F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.84F, KeyframeAnimations.degreeVec(-12.94F, 0.0F, -6.66F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.88F, KeyframeAnimations.degreeVec(-9.85F, 0.0F, -2.85F), AnimationChannel.Interpolations.LINEAR)
            ))
            .addAnimation("Root", new AnimationChannel(AnimationChannel.Targets.POSITION,
                    new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -0.375F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.04F, KeyframeAnimations.posVec(0.0F, -0.375F, 0.55F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.08F, KeyframeAnimations.posVec(0.0F, -0.375F, 1.06F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.12F, KeyframeAnimations.posVec(0.0F, -0.375F, 1.49F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.16F, KeyframeAnimations.posVec(0.0F, -0.375F, 1.8F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.2F, KeyframeAnimations.posVec(0.0F, 0.99F, 1.97F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.24F, KeyframeAnimations.posVec(0.0F, 3.63F, 1.99F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.28F, KeyframeAnimations.posVec(0.0F, 5.94F, 1.85F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.32F, KeyframeAnimations.posVec(0.0F, 7.73F, 1.58F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.36F, KeyframeAnimations.posVec(0.0F, 8.86F, 1.18F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.4F, KeyframeAnimations.posVec(0.0F, 9.25F, 0.68F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.44F, KeyframeAnimations.posVec(0.0F, 8.86F, 0.14F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.48F, KeyframeAnimations.posVec(0.0F, 7.73F, -0.42F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.52F, KeyframeAnimations.posVec(0.0F, 5.94F, -0.94F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.56F, KeyframeAnimations.posVec(0.0F, 3.63F, -1.39F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.6F, KeyframeAnimations.posVec(0.0F, 0.99F, -1.73F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.64F, KeyframeAnimations.posVec(0.0F, -0.375F, -1.94F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.68F, KeyframeAnimations.posVec(0.0F, -0.375F, -2.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.72F, KeyframeAnimations.posVec(0.0F, -0.375F, -1.9F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.76F, KeyframeAnimations.posVec(0.0F, -0.375F, -1.66F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.8F, KeyframeAnimations.posVec(0.0F, -0.375F, -1.29F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.84F, KeyframeAnimations.posVec(0.0F, -0.375F, -0.81F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.88F, KeyframeAnimations.posVec(0.0F, -0.375F, -0.28F), AnimationChannel.Interpolations.LINEAR)
            ))
            .addAnimation("Root", new AnimationChannel(AnimationChannel.Targets.SCALE,
                    new Keyframe(0.0F, KeyframeAnimations.scaleVec(1.0F, 0.775F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.08F, KeyframeAnimations.scaleVec(1.0F, 0.7781F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.12F, KeyframeAnimations.scaleVec(1.0F, 0.7668F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.16F, KeyframeAnimations.scaleVec(1.0F, 0.7402F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.2F, KeyframeAnimations.scaleVec(1.0F, 0.725F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.24F, KeyframeAnimations.scaleVec(1.0F, 1.2196F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.28F, KeyframeAnimations.scaleVec(1.0F, 1.4896F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.32F, KeyframeAnimations.scaleVec(1.0F, 1.5952F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.36F, KeyframeAnimations.scaleVec(1.0F, 1.5962F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.4F, KeyframeAnimations.scaleVec(1.0F, 1.5528F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.44F, KeyframeAnimations.scaleVec(1.0F, 1.525F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.48F, KeyframeAnimations.scaleVec(1.0F, 1.5329F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.52F, KeyframeAnimations.scaleVec(1.0F, 1.5578F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.56F, KeyframeAnimations.scaleVec(1.0F, 1.525F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.6F, KeyframeAnimations.scaleVec(1.0F, 1.3545F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.64F, KeyframeAnimations.scaleVec(1.0F, 1.1152F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.68F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.72F, KeyframeAnimations.scaleVec(1.0F, 0.8412F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.76F, KeyframeAnimations.scaleVec(1.0F, 0.7685F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.8F, KeyframeAnimations.scaleVec(1.0F, 0.7526F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.88F, KeyframeAnimations.scaleVec(1.0F, 0.775F, 1.0F), AnimationChannel.Interpolations.LINEAR)
            ))
            .build();

    public static final AnimationDefinition SHAKE_IDLE = AnimationDefinition.Builder.withLength(1.0F).looping()
            .addAnimation("Root", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.04F, KeyframeAnimations.degreeVec(0.0F, 0.12F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.08F, KeyframeAnimations.degreeVec(0.0F, -0.19F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.12F, KeyframeAnimations.degreeVec(0.0F, 0.19F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.16F, KeyframeAnimations.degreeVec(0.0F, -0.12F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.2F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.24F, KeyframeAnimations.degreeVec(0.0F, 0.12F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.28F, KeyframeAnimations.degreeVec(0.0F, -0.19F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.32F, KeyframeAnimations.degreeVec(0.0F, 0.19F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.36F, KeyframeAnimations.degreeVec(0.0F, -0.12F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.4F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.44F, KeyframeAnimations.degreeVec(0.0F, 0.12F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.48F, KeyframeAnimations.degreeVec(0.0F, -0.19F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.52F, KeyframeAnimations.degreeVec(0.0F, 0.19F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.56F, KeyframeAnimations.degreeVec(0.0F, -0.12F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.6F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.64F, KeyframeAnimations.degreeVec(0.0F, 0.12F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.68F, KeyframeAnimations.degreeVec(0.0F, -0.19F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.72F, KeyframeAnimations.degreeVec(0.0F, 0.19F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.76F, KeyframeAnimations.degreeVec(0.0F, -0.12F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.8F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.84F, KeyframeAnimations.degreeVec(0.0F, 0.12F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.88F, KeyframeAnimations.degreeVec(0.0F, -0.19F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.92F, KeyframeAnimations.degreeVec(0.0F, 0.19F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.96F, KeyframeAnimations.degreeVec(0.0F, -0.12F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
            ))
            .addAnimation("Rubber_ducky", new AnimationChannel(AnimationChannel.Targets.POSITION,
                    new Keyframe(0.0F, KeyframeAnimations.posVec(-0.03F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.04F, KeyframeAnimations.posVec(0.03F, 0.02F, -0.02F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.08F, KeyframeAnimations.posVec(-0.01F, -0.03F, 0.03F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.12F, KeyframeAnimations.posVec(0.0F, 0.03F, -0.03F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.16F, KeyframeAnimations.posVec(0.02F, -0.02F, 0.02F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.2F, KeyframeAnimations.posVec(-0.03F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.24F, KeyframeAnimations.posVec(0.03F, 0.02F, -0.02F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.28F, KeyframeAnimations.posVec(-0.01F, -0.03F, 0.03F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.32F, KeyframeAnimations.posVec(0.0F, 0.03F, -0.03F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.36F, KeyframeAnimations.posVec(0.02F, -0.02F, 0.02F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.4F, KeyframeAnimations.posVec(-0.03F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.44F, KeyframeAnimations.posVec(0.03F, 0.02F, -0.02F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.48F, KeyframeAnimations.posVec(-0.01F, -0.03F, 0.03F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.52F, KeyframeAnimations.posVec(0.0F, 0.03F, -0.03F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.56F, KeyframeAnimations.posVec(0.02F, -0.02F, 0.02F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.6F, KeyframeAnimations.posVec(-0.03F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.64F, KeyframeAnimations.posVec(0.03F, 0.02F, -0.02F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.68F, KeyframeAnimations.posVec(-0.01F, -0.03F, 0.03F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.72F, KeyframeAnimations.posVec(0.0F, 0.03F, -0.03F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.76F, KeyframeAnimations.posVec(0.02F, -0.02F, 0.02F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.8F, KeyframeAnimations.posVec(-0.03F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.84F, KeyframeAnimations.posVec(0.03F, 0.02F, -0.02F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.88F, KeyframeAnimations.posVec(-0.01F, -0.03F, 0.03F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.92F, KeyframeAnimations.posVec(0.0F, 0.03F, -0.03F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.96F, KeyframeAnimations.posVec(0.02F, -0.02F, 0.02F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.0F, KeyframeAnimations.posVec(-0.03F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
            ))
            .addAnimation("Left_tendril_eye", new AnimationChannel(AnimationChannel.Targets.SCALE,
                    new Keyframe(0.0F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
            ))
            .addAnimation("Left_tendril", new AnimationChannel(AnimationChannel.Targets.SCALE,
                    new Keyframe(0.0F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
            ))
            .addAnimation("Left_tendril2", new AnimationChannel(AnimationChannel.Targets.SCALE,
                    new Keyframe(0.0F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
            ))
            .addAnimation("Right_tendril2", new AnimationChannel(AnimationChannel.Targets.SCALE,
                    new Keyframe(0.0F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
            ))
            .addAnimation("Right_tendril", new AnimationChannel(AnimationChannel.Targets.SCALE,
                    new Keyframe(0.0F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
            ))
            .addAnimation("tail", new AnimationChannel(AnimationChannel.Targets.SCALE,
                    new Keyframe(0.0F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
            ))
            .addAnimation("Right_tendril_eye", new AnimationChannel(AnimationChannel.Targets.SCALE,
                    new Keyframe(0.0F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
            ))
            .build();

    public static final AnimationDefinition TRANSFORM = AnimationDefinition.Builder.withLength(2.56F)
            .addAnimation("Rubber_ducky", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.2F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -15.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.24F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 7.07F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.28F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 14.37F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.32F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 13.73F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.36F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 12.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.44F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 12.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.56F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 15.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.6F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -6.9F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.64F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -5.12F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.68F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.12F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.28F, KeyframeAnimations.degreeVec(-0.32F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.36F, KeyframeAnimations.degreeVec(-0.6F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.4F, KeyframeAnimations.degreeVec(-0.66F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.44F, KeyframeAnimations.degreeVec(-0.61F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.48F, KeyframeAnimations.degreeVec(-0.4F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.52F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.56F, KeyframeAnimations.degreeVec(0.61F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.6F, KeyframeAnimations.degreeVec(1.45F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.64F, KeyframeAnimations.degreeVec(2.47F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.8F, KeyframeAnimations.degreeVec(7.43F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.84F, KeyframeAnimations.degreeVec(8.49F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.88F, KeyframeAnimations.degreeVec(9.3F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.92F, KeyframeAnimations.degreeVec(9.82F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.96F, KeyframeAnimations.degreeVec(10.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
            ))
            .addAnimation("Rubber_ducky", new AnimationChannel(AnimationChannel.Targets.POSITION,
                    new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.04F, KeyframeAnimations.posVec(-0.42F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.08F, KeyframeAnimations.posVec(-0.48F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.12F, KeyframeAnimations.posVec(-0.44F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.24F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.44F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.56F, KeyframeAnimations.posVec(0.31F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.68F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.12F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.2F, KeyframeAnimations.posVec(0.0F, -0.06F, 0.01F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.24F, KeyframeAnimations.posVec(0.0F, -0.13F, 0.01F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.36F, KeyframeAnimations.posVec(0.0F, -0.42F, 0.04F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.4F, KeyframeAnimations.posVec(0.0F, -0.46F, 0.05F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.44F, KeyframeAnimations.posVec(0.0F, -0.43F, 0.04F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.48F, KeyframeAnimations.posVec(0.0F, -0.28F, 0.03F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.52F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.56F, KeyframeAnimations.posVec(0.0F, 0.43F, -0.04F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.6F, KeyframeAnimations.posVec(0.0F, 1.02F, -0.1F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.64F, KeyframeAnimations.posVec(0.0F, 1.75F, -0.17F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.68F, KeyframeAnimations.posVec(0.0F, 2.58F, -0.25F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.76F, KeyframeAnimations.posVec(0.0F, 4.39F, -0.43F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.8F, KeyframeAnimations.posVec(0.0F, 5.25F, -0.51F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.84F, KeyframeAnimations.posVec(0.0F, 5.99F, -0.58F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.88F, KeyframeAnimations.posVec(0.0F, 6.57F, -0.64F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.92F, KeyframeAnimations.posVec(0.0F, 6.94F, -0.68F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.96F, KeyframeAnimations.posVec(0.0F, 7.06F, -0.69F), AnimationChannel.Interpolations.LINEAR)
            ))
            .addAnimation("Rubber_ducky", new AnimationChannel(AnimationChannel.Targets.SCALE,
                    new Keyframe(0.0F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.04F, KeyframeAnimations.scaleVec(0.8984F, 1.0F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.08F, KeyframeAnimations.scaleVec(0.8843F, 1.0F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.12F, KeyframeAnimations.scaleVec(0.8938F, 1.0F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.24F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.32F, KeyframeAnimations.scaleVec(1.0F, 1.125F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.4F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.44F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.56F, KeyframeAnimations.scaleVec(0.8938F, 1.0F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.68F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.LINEAR)
            ))
            .addAnimation("Left_tendril_eye", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(1.08F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 40.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.12F, KeyframeAnimations.degreeVec(-1.12F, 0.14F, 40.73F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.16F, KeyframeAnimations.degreeVec(-4.19F, 0.51F, 42.72F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.2F, KeyframeAnimations.degreeVec(-8.44F, 1.03F, 45.49F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.24F, KeyframeAnimations.degreeVec(-12.89F, 1.57F, 48.38F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.28F, KeyframeAnimations.degreeVec(-16.62F, 2.03F, 50.81F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.32F, KeyframeAnimations.degreeVec(-19.09F, 2.33F, 52.41F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.36F, KeyframeAnimations.degreeVec(-20.2F, 2.46F, 53.14F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.4F, KeyframeAnimations.degreeVec(-20.28F, 2.47F, 53.19F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.48F, KeyframeAnimations.degreeVec(-19.37F, 2.36F, 52.6F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.56F, KeyframeAnimations.degreeVec(-19.09F, 2.33F, 52.41F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.6F, KeyframeAnimations.degreeVec(-19.23F, 2.67F, 53.55F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.64F, KeyframeAnimations.degreeVec(-19.44F, 3.15F, 55.13F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.68F, KeyframeAnimations.degreeVec(-19.34F, 2.91F, 54.35F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.72F, KeyframeAnimations.degreeVec(-18.57F, 1.13F, 48.44F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.76F, KeyframeAnimations.degreeVec(-16.76F, -3.04F, 34.63F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.8F, KeyframeAnimations.degreeVec(-13.95F, -9.53F, 13.15F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.84F, KeyframeAnimations.degreeVec(-12.14F, -13.7F, -0.66F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.88F, KeyframeAnimations.degreeVec(-11.37F, -15.49F, -6.57F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.92F, KeyframeAnimations.degreeVec(-11.27F, -15.72F, -7.35F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.96F, KeyframeAnimations.degreeVec(-11.47F, -15.25F, -5.78F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.0F, KeyframeAnimations.degreeVec(-11.62F, -14.9F, -4.63F), AnimationChannel.Interpolations.LINEAR)
            ))
            .addAnimation("Left_tendril_eye", new AnimationChannel(AnimationChannel.Targets.POSITION,
                    new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.04F, KeyframeAnimations.posVec(-0.48F, -0.46F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.08F, KeyframeAnimations.posVec(-0.9F, -0.86F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.12F, KeyframeAnimations.posVec(-1.29F, -1.23F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.16F, KeyframeAnimations.posVec(-1.62F, -1.55F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.2F, KeyframeAnimations.posVec(-1.92F, -1.84F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.24F, KeyframeAnimations.posVec(-2.18F, -2.09F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.28F, KeyframeAnimations.posVec(-2.4F, -2.3F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.32F, KeyframeAnimations.posVec(-2.59F, -2.48F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.36F, KeyframeAnimations.posVec(-2.75F, -2.63F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.4F, KeyframeAnimations.posVec(-2.88F, -2.75F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.44F, KeyframeAnimations.posVec(-2.98F, -2.85F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.52F, KeyframeAnimations.posVec(-3.11F, -2.97F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.56F, KeyframeAnimations.posVec(-3.14F, -3.01F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.6F, KeyframeAnimations.posVec(-3.16F, -3.02F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.72F, KeyframeAnimations.posVec(-3.13F, -2.99F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.96F, KeyframeAnimations.posVec(-2.92F, -2.8F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.04F, KeyframeAnimations.posVec(-2.88F, -2.76F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.08F, KeyframeAnimations.posVec(-2.88F, -2.75F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.12F, KeyframeAnimations.posVec(-2.89F, -2.77F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.24F, KeyframeAnimations.posVec(-3.01F, -2.88F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.28F, KeyframeAnimations.posVec(-3.02F, -2.89F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.32F, KeyframeAnimations.posVec(-2.99F, -2.86F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.36F, KeyframeAnimations.posVec(-2.91F, -2.78F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.4F, KeyframeAnimations.posVec(-2.75F, -2.63F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.44F, KeyframeAnimations.posVec(-2.51F, -2.4F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.48F, KeyframeAnimations.posVec(-2.17F, -2.08F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.52F, KeyframeAnimations.posVec(-1.71F, -1.64F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.56F, KeyframeAnimations.posVec(-1.16F, -1.11F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.6F, KeyframeAnimations.posVec(-0.7F, -0.67F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.64F, KeyframeAnimations.posVec(-0.36F, -0.35F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.68F, KeyframeAnimations.posVec(-0.12F, -0.12F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.72F, KeyframeAnimations.posVec(0.03F, 0.03F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.76F, KeyframeAnimations.posVec(0.11F, 0.11F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.8F, KeyframeAnimations.posVec(0.14F, 0.14F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.84F, KeyframeAnimations.posVec(0.13F, 0.13F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.96F, KeyframeAnimations.posVec(0.02F, 0.02F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
            ))
            .addAnimation("Left_tendril_eye", new AnimationChannel(AnimationChannel.Targets.SCALE,
                    new Keyframe(0.0F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.04F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.1655F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.08F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.3142F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.12F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.4471F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.16F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.5648F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.2F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.6682F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.24F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.7582F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.28F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.8356F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.32F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.9012F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.36F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.9558F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.44F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 1.0353F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.52F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 1.0809F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.6F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 1.0989F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.76F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 1.0791F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.96F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 1.0173F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.12F, KeyframeAnimations.scaleVec(-0.0055F, -0.0055F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.24F, KeyframeAnimations.scaleVec(-0.0461F, -0.0461F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.28F, KeyframeAnimations.scaleVec(-0.0498F, -0.0498F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.32F, KeyframeAnimations.scaleVec(-0.0398F, -0.0398F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.36F, KeyframeAnimations.scaleVec(-0.0106F, -0.0106F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.4F, KeyframeAnimations.scaleVec(0.043F, 0.043F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.44F, KeyframeAnimations.scaleVec(0.1264F, 0.1264F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.48F, KeyframeAnimations.scaleVec(0.2448F, 0.2448F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.52F, KeyframeAnimations.scaleVec(0.4037F, 0.4037F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.56F, KeyframeAnimations.scaleVec(0.5963F, 0.5963F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.6F, KeyframeAnimations.scaleVec(0.7552F, 0.7552F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.64F, KeyframeAnimations.scaleVec(0.8736F, 0.8736F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.68F, KeyframeAnimations.scaleVec(0.957F, 0.957F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.72F, KeyframeAnimations.scaleVec(1.0106F, 1.0106F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.76F, KeyframeAnimations.scaleVec(1.0398F, 1.0398F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.8F, KeyframeAnimations.scaleVec(1.0498F, 1.0498F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.96F, KeyframeAnimations.scaleVec(1.0055F, 1.0055F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.0F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.LINEAR)
            ))
            .addAnimation("Left_tendril", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.12F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -60.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.24F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -100.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.44F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -67.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.6F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -71.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.8F, KeyframeAnimations.degreeVec(-36.17F, 8.37F, -42.74F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.08F, KeyframeAnimations.degreeVec(-36.17F, 8.37F, -42.74F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.6F, KeyframeAnimations.degreeVec(-34.22F, 14.0F, -34.37F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.0F, KeyframeAnimations.degreeVec(-32.72F, 18.33F, -27.92F), AnimationChannel.Interpolations.LINEAR)
            ))
            .addAnimation("Left_tendril", new AnimationChannel(AnimationChannel.Targets.SCALE,
                    new Keyframe(0.0F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.12F, KeyframeAnimations.scaleVec(0.0F, 1.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.24F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.LINEAR)
            ))
            .addAnimation("Left_tendril2", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(1.08F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.16F, KeyframeAnimations.degreeVec(5.33F, 2.99F, -8.07F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.2F, KeyframeAnimations.degreeVec(7.86F, 4.41F, -11.9F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.24F, KeyframeAnimations.degreeVec(10.23F, 5.73F, -15.49F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.28F, KeyframeAnimations.degreeVec(12.39F, 6.95F, -18.76F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.32F, KeyframeAnimations.degreeVec(14.29F, 8.02F, -21.65F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.36F, KeyframeAnimations.degreeVec(15.91F, 8.92F, -24.1F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.4F, KeyframeAnimations.degreeVec(17.2F, 9.65F, -26.06F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.44F, KeyframeAnimations.degreeVec(18.15F, 10.18F, -27.49F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.52F, KeyframeAnimations.degreeVec(18.91F, 10.61F, -28.65F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.56F, KeyframeAnimations.degreeVec(18.93F, 10.46F, -28.24F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.6F, KeyframeAnimations.degreeVec(18.98F, 10.01F, -27.05F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.64F, KeyframeAnimations.degreeVec(19.06F, 9.3F, -25.14F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.68F, KeyframeAnimations.degreeVec(19.17F, 8.38F, -22.66F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.72F, KeyframeAnimations.degreeVec(19.29F, 7.31F, -19.78F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.8F, KeyframeAnimations.degreeVec(19.55F, 5.01F, -13.58F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.84F, KeyframeAnimations.degreeVec(19.68F, 3.93F, -10.69F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.88F, KeyframeAnimations.degreeVec(19.78F, 3.01F, -8.21F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.92F, KeyframeAnimations.degreeVec(19.86F, 2.3F, -6.3F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.96F, KeyframeAnimations.degreeVec(19.91F, 1.86F, -5.11F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.0F, KeyframeAnimations.degreeVec(19.93F, 1.71F, -4.7F), AnimationChannel.Interpolations.LINEAR)
            ))
            .addAnimation("Left_tendril2", new AnimationChannel(AnimationChannel.Targets.SCALE,
                    new Keyframe(1.08F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.28F, KeyframeAnimations.scaleVec(0.3349F, 0.3349F, 0.3349F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.44F, KeyframeAnimations.scaleVec(0.5767F, 0.5767F, 0.5767F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.6F, KeyframeAnimations.scaleVec(0.7757F, 0.7757F, 0.7757F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.72F, KeyframeAnimations.scaleVec(0.8879F, 0.8879F, 0.8879F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.84F, KeyframeAnimations.scaleVec(0.9629F, 0.9629F, 0.9629F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.0F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.LINEAR)
            ))
            .addAnimation("Right_tendril2", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(1.08F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.16F, KeyframeAnimations.degreeVec(5.33F, -2.99F, 8.07F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.2F, KeyframeAnimations.degreeVec(7.86F, -4.41F, 11.9F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.24F, KeyframeAnimations.degreeVec(10.23F, -5.73F, 15.49F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.28F, KeyframeAnimations.degreeVec(12.39F, -6.95F, 18.76F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.32F, KeyframeAnimations.degreeVec(14.29F, -8.02F, 21.65F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.36F, KeyframeAnimations.degreeVec(15.91F, -8.92F, 24.1F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.4F, KeyframeAnimations.degreeVec(17.2F, -9.65F, 26.06F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.44F, KeyframeAnimations.degreeVec(18.15F, -10.18F, 27.49F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.52F, KeyframeAnimations.degreeVec(18.91F, -10.61F, 28.65F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.56F, KeyframeAnimations.degreeVec(18.93F, -10.46F, 28.24F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.6F, KeyframeAnimations.degreeVec(18.98F, -10.01F, 27.05F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.64F, KeyframeAnimations.degreeVec(19.06F, -9.3F, 25.14F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.68F, KeyframeAnimations.degreeVec(19.17F, -8.38F, 22.66F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.72F, KeyframeAnimations.degreeVec(19.29F, -7.31F, 19.78F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.8F, KeyframeAnimations.degreeVec(19.55F, -5.01F, 13.58F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.84F, KeyframeAnimations.degreeVec(19.68F, -3.93F, 10.69F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.88F, KeyframeAnimations.degreeVec(19.78F, -3.01F, 8.21F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.92F, KeyframeAnimations.degreeVec(19.86F, -2.3F, 6.3F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.96F, KeyframeAnimations.degreeVec(19.91F, -1.86F, 5.11F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.0F, KeyframeAnimations.degreeVec(19.93F, -1.71F, 4.7F), AnimationChannel.Interpolations.LINEAR)
            ))
            .addAnimation("Right_tendril2", new AnimationChannel(AnimationChannel.Targets.SCALE,
                    new Keyframe(1.08F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.28F, KeyframeAnimations.scaleVec(0.3349F, 0.3349F, 0.3349F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.44F, KeyframeAnimations.scaleVec(0.5767F, 0.5767F, 0.5767F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.6F, KeyframeAnimations.scaleVec(0.7757F, 0.7757F, 0.7757F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.72F, KeyframeAnimations.scaleVec(0.8879F, 0.8879F, 0.8879F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.84F, KeyframeAnimations.scaleVec(0.9629F, 0.9629F, 0.9629F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.0F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.LINEAR)
            ))
            .addAnimation("Right_tendril", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0.44F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.56F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 60.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.68F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 100.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.84F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 119.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.04F, KeyframeAnimations.degreeVec(-36.17F, -8.37F, 42.74F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.08F, KeyframeAnimations.degreeVec(-36.17F, -8.37F, 42.74F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.6F, KeyframeAnimations.degreeVec(-34.22F, -14.0F, 34.37F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.0F, KeyframeAnimations.degreeVec(-32.72F, -18.33F, 27.92F), AnimationChannel.Interpolations.LINEAR)
            ))
            .addAnimation("Right_tendril", new AnimationChannel(AnimationChannel.Targets.SCALE,
                    new Keyframe(0.44F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.56F, KeyframeAnimations.scaleVec(1.0F, 0.0F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.76F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.88F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.96F, KeyframeAnimations.scaleVec(1.0F, 1.6125F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.0F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.LINEAR)
            ))
            .addAnimation("tail", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0.68F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.72F, KeyframeAnimations.degreeVec(8.85F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.76F, KeyframeAnimations.degreeVec(20.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.8F, KeyframeAnimations.degreeVec(20.79F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.84F, KeyframeAnimations.degreeVec(20.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.88F, KeyframeAnimations.degreeVec(20.99F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.92F, KeyframeAnimations.degreeVec(23.26F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.96F, KeyframeAnimations.degreeVec(25.36F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.0F, KeyframeAnimations.degreeVec(26.32F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.04F, KeyframeAnimations.degreeVec(26.31F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.08F, KeyframeAnimations.degreeVec(26.06F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.12F, KeyframeAnimations.degreeVec(26.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.16F, KeyframeAnimations.degreeVec(26.05F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.2F, KeyframeAnimations.degreeVec(26.34F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.24F, KeyframeAnimations.degreeVec(27.01F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.32F, KeyframeAnimations.degreeVec(28.88F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.36F, KeyframeAnimations.degreeVec(29.25F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.4F, KeyframeAnimations.degreeVec(28.47F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.44F, KeyframeAnimations.degreeVec(26.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.48F, KeyframeAnimations.degreeVec(21.54F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.52F, KeyframeAnimations.degreeVec(15.11F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.56F, KeyframeAnimations.degreeVec(7.14F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.6F, KeyframeAnimations.degreeVec(-1.6F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.64F, KeyframeAnimations.degreeVec(-10.07F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.68F, KeyframeAnimations.degreeVec(-17.15F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.72F, KeyframeAnimations.degreeVec(-21.85F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.76F, KeyframeAnimations.degreeVec(-23.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.8F, KeyframeAnimations.degreeVec(-11.76F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.84F, KeyframeAnimations.degreeVec(-1.72F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.88F, KeyframeAnimations.degreeVec(6.76F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.92F, KeyframeAnimations.degreeVec(13.79F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.96F, KeyframeAnimations.degreeVec(19.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.0F, KeyframeAnimations.degreeVec(23.99F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.04F, KeyframeAnimations.degreeVec(27.4F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.08F, KeyframeAnimations.degreeVec(29.85F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.12F, KeyframeAnimations.degreeVec(31.45F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.16F, KeyframeAnimations.degreeVec(32.33F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.2F, KeyframeAnimations.degreeVec(32.6F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.24F, KeyframeAnimations.degreeVec(32.39F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.28F, KeyframeAnimations.degreeVec(31.82F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.32F, KeyframeAnimations.degreeVec(31.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.4F, KeyframeAnimations.degreeVec(29.12F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.44F, KeyframeAnimations.degreeVec(28.3F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.48F, KeyframeAnimations.degreeVec(27.72F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.52F, KeyframeAnimations.degreeVec(27.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
            ))
            .addAnimation("tail", new AnimationChannel(AnimationChannel.Targets.POSITION,
                    new Keyframe(0.84F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.88F, KeyframeAnimations.posVec(0.0F, 0.13F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.92F, KeyframeAnimations.posVec(0.0F, 0.44F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.96F, KeyframeAnimations.posVec(0.0F, 0.71F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.0F, KeyframeAnimations.posVec(0.0F, 0.84F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.04F, KeyframeAnimations.posVec(0.0F, 0.84F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.08F, KeyframeAnimations.posVec(0.0F, 0.81F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.6F, KeyframeAnimations.posVec(0.0F, 0.8F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.76F, KeyframeAnimations.posVec(0.0F, 0.8F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.8F, KeyframeAnimations.posVec(0.0F, 0.62F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.84F, KeyframeAnimations.posVec(0.0F, 0.46F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.88F, KeyframeAnimations.posVec(0.0F, 0.33F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.92F, KeyframeAnimations.posVec(0.0F, 0.22F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.96F, KeyframeAnimations.posVec(0.0F, 0.13F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.04F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.08F, KeyframeAnimations.posVec(0.0F, -0.04F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.16F, KeyframeAnimations.posVec(0.0F, -0.08F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.28F, KeyframeAnimations.posVec(0.0F, -0.07F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.52F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
            ))
            .addAnimation("tail", new AnimationChannel(AnimationChannel.Targets.SCALE,
                    new Keyframe(0.0F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.04F, KeyframeAnimations.scaleVec(-0.02F, -0.02F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.12F, KeyframeAnimations.scaleVec(-0.1152F, -0.1152F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.16F, KeyframeAnimations.scaleVec(-0.1474F, -0.1474F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.2F, KeyframeAnimations.scaleVec(-0.1407F, -0.1407F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.24F, KeyframeAnimations.scaleVec(-0.0735F, -0.0735F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.28F, KeyframeAnimations.scaleVec(0.0756F, 0.0756F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.32F, KeyframeAnimations.scaleVec(0.3282F, 0.3282F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.36F, KeyframeAnimations.scaleVec(0.6718F, 0.6718F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.4F, KeyframeAnimations.scaleVec(0.9244F, 0.9244F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.44F, KeyframeAnimations.scaleVec(1.0735F, 1.0735F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.48F, KeyframeAnimations.scaleVec(1.1407F, 1.1407F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.52F, KeyframeAnimations.scaleVec(1.1474F, 1.1474F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.56F, KeyframeAnimations.scaleVec(1.1152F, 1.1152F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.64F, KeyframeAnimations.scaleVec(1.02F, 1.02F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.68F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.72F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 0.4424F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.76F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.8F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0396F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.84F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.LINEAR)
            ))
            .addAnimation("Right_tendril_eye", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(1.08F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -40.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.12F, KeyframeAnimations.degreeVec(-1.12F, -0.14F, -40.73F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.16F, KeyframeAnimations.degreeVec(-4.19F, -0.51F, -42.72F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.2F, KeyframeAnimations.degreeVec(-8.44F, -1.03F, -45.49F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.24F, KeyframeAnimations.degreeVec(-12.89F, -1.57F, -48.38F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.28F, KeyframeAnimations.degreeVec(-16.62F, -2.03F, -50.81F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.32F, KeyframeAnimations.degreeVec(-19.09F, -2.33F, -52.41F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.36F, KeyframeAnimations.degreeVec(-20.2F, -2.46F, -53.14F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.4F, KeyframeAnimations.degreeVec(-20.28F, -2.47F, -53.19F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.48F, KeyframeAnimations.degreeVec(-19.37F, -2.36F, -52.6F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.56F, KeyframeAnimations.degreeVec(-19.09F, -2.33F, -52.41F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.6F, KeyframeAnimations.degreeVec(-19.23F, -2.67F, -53.55F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.64F, KeyframeAnimations.degreeVec(-19.44F, -3.15F, -55.13F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.68F, KeyframeAnimations.degreeVec(-19.34F, -2.91F, -54.35F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.72F, KeyframeAnimations.degreeVec(-18.57F, -1.13F, -48.44F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.76F, KeyframeAnimations.degreeVec(-16.76F, 3.04F, -34.63F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.8F, KeyframeAnimations.degreeVec(-13.95F, 9.53F, -13.15F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.84F, KeyframeAnimations.degreeVec(-12.14F, 13.7F, 0.66F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.88F, KeyframeAnimations.degreeVec(-11.37F, 15.49F, 6.57F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.92F, KeyframeAnimations.degreeVec(-11.27F, 15.72F, 7.35F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.96F, KeyframeAnimations.degreeVec(-11.47F, 15.25F, 5.78F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.0F, KeyframeAnimations.degreeVec(-11.62F, 14.9F, 4.63F), AnimationChannel.Interpolations.LINEAR)
            ))
            .addAnimation("Right_tendril_eye", new AnimationChannel(AnimationChannel.Targets.POSITION,
                    new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.04F, KeyframeAnimations.posVec(0.48F, -0.46F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.08F, KeyframeAnimations.posVec(0.9F, -0.86F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.12F, KeyframeAnimations.posVec(1.29F, -1.23F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.16F, KeyframeAnimations.posVec(1.62F, -1.55F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.2F, KeyframeAnimations.posVec(1.92F, -1.84F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.24F, KeyframeAnimations.posVec(2.18F, -2.09F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.28F, KeyframeAnimations.posVec(2.4F, -2.3F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.32F, KeyframeAnimations.posVec(2.59F, -2.48F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.36F, KeyframeAnimations.posVec(2.75F, -2.63F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.4F, KeyframeAnimations.posVec(2.88F, -2.75F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.44F, KeyframeAnimations.posVec(2.98F, -2.85F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.52F, KeyframeAnimations.posVec(3.11F, -2.97F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.56F, KeyframeAnimations.posVec(3.14F, -3.01F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.6F, KeyframeAnimations.posVec(3.16F, -3.02F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.72F, KeyframeAnimations.posVec(3.13F, -2.99F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.96F, KeyframeAnimations.posVec(2.92F, -2.8F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.04F, KeyframeAnimations.posVec(2.88F, -2.76F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.08F, KeyframeAnimations.posVec(2.87F, -2.75F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.12F, KeyframeAnimations.posVec(2.89F, -2.77F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.24F, KeyframeAnimations.posVec(3.01F, -2.88F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.28F, KeyframeAnimations.posVec(3.02F, -2.89F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.32F, KeyframeAnimations.posVec(2.99F, -2.86F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.36F, KeyframeAnimations.posVec(2.91F, -2.78F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.4F, KeyframeAnimations.posVec(2.75F, -2.63F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.44F, KeyframeAnimations.posVec(2.51F, -2.4F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.48F, KeyframeAnimations.posVec(2.17F, -2.08F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.52F, KeyframeAnimations.posVec(1.71F, -1.64F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.56F, KeyframeAnimations.posVec(1.16F, -1.11F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.6F, KeyframeAnimations.posVec(0.7F, -0.67F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.64F, KeyframeAnimations.posVec(0.36F, -0.35F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.68F, KeyframeAnimations.posVec(0.12F, -0.12F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.72F, KeyframeAnimations.posVec(-0.03F, 0.03F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.76F, KeyframeAnimations.posVec(-0.11F, 0.11F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.8F, KeyframeAnimations.posVec(-0.14F, 0.14F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.84F, KeyframeAnimations.posVec(-0.13F, 0.13F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.96F, KeyframeAnimations.posVec(-0.02F, 0.02F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
            ))
            .addAnimation("Right_tendril_eye", new AnimationChannel(AnimationChannel.Targets.SCALE,
                    new Keyframe(0.0F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.04F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.1655F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.08F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.3142F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.12F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.4471F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.16F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.5648F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.2F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.6682F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.24F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.7582F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.28F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.8356F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.32F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.9012F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.36F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.9558F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.44F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 1.0353F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.52F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 1.0809F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.6F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 1.0989F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.76F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 1.0791F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(0.96F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 1.0173F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.12F, KeyframeAnimations.scaleVec(-0.0055F, -0.0055F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.24F, KeyframeAnimations.scaleVec(-0.0461F, -0.0461F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.28F, KeyframeAnimations.scaleVec(-0.0498F, -0.0498F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.32F, KeyframeAnimations.scaleVec(-0.0398F, -0.0398F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.36F, KeyframeAnimations.scaleVec(-0.0106F, -0.0106F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.4F, KeyframeAnimations.scaleVec(0.043F, 0.043F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.44F, KeyframeAnimations.scaleVec(0.1264F, 0.1264F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.48F, KeyframeAnimations.scaleVec(0.2448F, 0.2448F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.52F, KeyframeAnimations.scaleVec(0.4037F, 0.4037F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.56F, KeyframeAnimations.scaleVec(0.5963F, 0.5963F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.6F, KeyframeAnimations.scaleVec(0.7552F, 0.7552F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.64F, KeyframeAnimations.scaleVec(0.8736F, 0.8736F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.68F, KeyframeAnimations.scaleVec(0.957F, 0.957F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.72F, KeyframeAnimations.scaleVec(1.0106F, 1.0106F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.76F, KeyframeAnimations.scaleVec(1.0398F, 1.0398F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.8F, KeyframeAnimations.scaleVec(1.0498F, 1.0498F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(1.96F, KeyframeAnimations.scaleVec(1.0055F, 1.0055F, 1.0F), AnimationChannel.Interpolations.LINEAR),
                    new Keyframe(2.0F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.LINEAR)
            ))
            .build();
}
