package io.github.chaosawakens.common.util;

public class FunkyMonkUtil {
	
	/**
	 * BOOOOOOOOOLEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAN
	 * @param boo_lean BOOOOOOOOOLEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAN
	 * @return BOOOOOOOOOLEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAN
	 */
	public static boolean dotNextBoolean(Boolean boo_lean) { // BOOOOOOOOOLEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAN
		return boo_lean;
	}

}
