plugins {
    id("org.spongepowered.gradle.vanilla")
}

base {
    archivesName = "${mod_name}-${mod_version}-${minecraft_version}-common"
}

minecraft {
    version(minecraft_version)

    if (file("src/main/resources/${mod_id}.accessWidener").exists()){
        accessWideners(file("src/main/resources/${mod_id}.accessWidener"))
    }
}

dependencies {
    // Base
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    compileOnly group: 'io.github.llamalad7', name: 'mixinextras-common', version:'0.5.0-rc.2'
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = base.archivesName.get()
            version = mod_version

            artifact jar
            artifact sourcesJar
            artifact javadocJar
        }
    }
}