package io.github.chaosawakens.common.registry;

import io.github.chaosawakens.CAConstants;
import io.github.chaosawakens.api.asm.annotations.RegistrarEntry;
import it.unimi.dsi.fastutil.objects.ObjectArrayList;
import net.minecraft.Util;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.storage.loot.LootPool;
import net.minecraft.world.level.storage.loot.LootTable;
import net.minecraft.world.level.storage.loot.entries.LootItem;
import net.minecraft.world.level.storage.loot.functions.SetItemCountFunction;
import net.minecraft.world.level.storage.loot.functions.SetNbtFunction;
import net.minecraft.world.level.storage.loot.predicates.LootItemRandomChanceCondition;
import net.minecraft.world.level.storage.loot.providers.number.ConstantValue;
import net.minecraft.world.level.storage.loot.providers.number.UniformGenerator;
import org.apache.commons.lang3.tuple.Pair;

import java.util.function.Supplier;

@RegistrarEntry
public class CAChestLootTables {
    public static final ObjectArrayList<Pair<ResourceLocation, Supplier<LootTable.Builder>>> LOOT_TABLES = new ObjectArrayList<>();

    public static final ResourceLocation ACACIA_ENT_TREE_LOOT_TABLE = registerTable("chests/ent_tree/acacia_loot", () -> LootTable.lootTable()
            .withPool(LootPool.lootPool()
                    // Common Loot
                    .setRolls(ConstantValue.exactly(4))
                    .add(LootItem.lootTableItem(Items.ACACIA_PLANKS)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(8, 14)))
                            .setWeight(70))
                    .add(LootItem.lootTableItem(Items.ACACIA_PLANKS)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(8, 14)))
                            .setWeight(70))
                    .add(LootItem.lootTableItem(Items.ACACIA_PLANKS)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(8, 14)))
                            .setWeight(70))
                    .add(LootItem.lootTableItem(Items.ACACIA_PLANKS)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(8, 14)))
                            .setWeight(70))
                    .add(LootItem.lootTableItem(Items.ACACIA_LOG)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 5)))
                            .setWeight(100))
                    .add(LootItem.lootTableItem(Items.ACACIA_LOG)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 5)))
                            .setWeight(100))
                    .add(LootItem.lootTableItem(Items.ACACIA_LOG)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 5)))
                            .setWeight(100))
                    .add(LootItem.lootTableItem(Items.ACACIA_LOG)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 5)))
                            .setWeight(100)))
            .withPool(LootPool.lootPool()
                    // Common Loot
                    .setRolls(ConstantValue.exactly(1))
                    .add(LootItem.lootTableItem(Items.ACACIA_LEAVES)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 7)))
                            .setWeight(100))
                    .add(LootItem.lootTableItem(Items.ACACIA_LEAVES)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5)))
                            .setWeight(50)))
            .withPool(LootPool.lootPool()
                    // Common Loot
                    .setRolls(ConstantValue.exactly(2))
                    .add(LootItem.lootTableItem(Items.GRASS)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5)))
                            .setWeight(25))
                    .add(LootItem.lootTableItem(Items.GRASS)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5)))
                            .setWeight(25))
                    .add(LootItem.lootTableItem(Items.ACACIA_SAPLING)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 7)))
                            .setWeight(50))
                    .add(LootItem.lootTableItem(Items.ACACIA_SAPLING)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 7)))
                            .setWeight(50)))
            .withPool(LootPool.lootPool()
                    // Rare Loot
                    .setRolls(UniformGenerator.between(0, 2))
                    .add(LootItem.lootTableItem(Items.DIAMOND)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(0, 2)))
                            .when(LootItemRandomChanceCondition.randomChance(0.85F)))
                    .add(LootItem.lootTableItem(Items.EMERALD)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(0, 2)))
                            .when(LootItemRandomChanceCondition.randomChance(0.85F)))
                    /*.add(LootItem.lootTableItem(CAItems.TIGERS_EYE.get())
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(0, 2)))
                            .when(LootItemRandomChanceCondition.randomChance(0.35F)))
                    .add(LootItem.lootTableItem(CAItems.KUNZITE.get())
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(0, 2)))
                            .when(LootItemRandomChanceCondition.randomChance(0.35F)))*/)
            .withPool(LootPool.lootPool()
                    // Rare Loot
                    .setRolls(UniformGenerator.between(1, 2))
                    .add(LootItem.lootTableItem(Items.GOLD_INGOT)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(2, 7)))
                            .when(LootItemRandomChanceCondition.randomChance(0.75F))
                            .setWeight(110))
                    .add(LootItem.lootTableItem(Items.GOLD_INGOT)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(2, 7)))
                            .when(LootItemRandomChanceCondition.randomChance(0.75F))
                            .setWeight(110)))
            .withPool(LootPool.lootPool()
                    // Very Rare Loot
                    .setRolls(UniformGenerator.between(0, 1))
                    .add(LootItem.lootTableItem(Items.GOLD_BLOCK)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(0, 2)))
                            .when(LootItemRandomChanceCondition.randomChance(0.35F))
                            .setWeight(25))));

    public static final ResourceLocation BIRCH_ENT_TREE_LOOT_TABLE = registerTable("chests/ent_tree/birch_loot", () -> LootTable.lootTable()
            .withPool(LootPool.lootPool()
                    // Common Loot
                    .setRolls(ConstantValue.exactly(4))
                    .add(LootItem.lootTableItem(Items.BIRCH_PLANKS)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(8, 14)))
                            .setWeight(70))
                    .add(LootItem.lootTableItem(Items.BIRCH_PLANKS)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(8, 14)))
                            .setWeight(70))
                    .add(LootItem.lootTableItem(Items.BIRCH_PLANKS)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(8, 14)))
                            .setWeight(70))
                    .add(LootItem.lootTableItem(Items.BIRCH_PLANKS)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(8, 14)))
                            .setWeight(70))
                    .add(LootItem.lootTableItem(Items.BIRCH_LOG)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 5)))
                            .setWeight(100))
                    .add(LootItem.lootTableItem(Items.BIRCH_LOG)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 5)))
                            .setWeight(100))
                    .add(LootItem.lootTableItem(Items.BIRCH_LOG)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 5)))
                            .setWeight(100))
                    .add(LootItem.lootTableItem(Items.BIRCH_LOG)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 5)))
                            .setWeight(100)))
            .withPool(LootPool.lootPool()
                    // Common Loot
                    .setRolls(ConstantValue.exactly(1))
                    .add(LootItem.lootTableItem(Items.BIRCH_LEAVES)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 7)))
                            .setWeight(100))
                    .add(LootItem.lootTableItem(Items.BIRCH_LEAVES)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5)))
                            .setWeight(50)))
            .withPool(LootPool.lootPool()
                    // Common Loot
                    .setRolls(ConstantValue.exactly(2))
                    .add(LootItem.lootTableItem(Items.BIRCH_LEAVES)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5)))
                            .setWeight(25))
                    .add(LootItem.lootTableItem(Items.BIRCH_LEAVES)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5)))
                            .setWeight(25))
                    .add(LootItem.lootTableItem(Items.BIRCH_SAPLING)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 7)))
                            .setWeight(50))
                    .add(LootItem.lootTableItem(Items.BIRCH_SAPLING)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 7)))
                            .setWeight(50)))
            .withPool(LootPool.lootPool()
                    // Rare Loot
                    .setRolls(UniformGenerator.between(0, 2))
                    .add(LootItem.lootTableItem(Items.DIAMOND)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(0, 2)))
                            .when(LootItemRandomChanceCondition.randomChance(0.85F)))
                    .add(LootItem.lootTableItem(Items.EMERALD)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(0, 2)))
                            .when(LootItemRandomChanceCondition.randomChance(0.85F)))
                    /*.add(LootItem.lootTableItem(CAItems.TIGERS_EYE.get())
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(0, 2)))
                            .when(LootItemRandomChanceCondition.randomChance(0.35F)))*/
                    .add(LootItem.lootTableItem(CAItems.KUNZITE.get())
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(0, 2)))
                            .when(LootItemRandomChanceCondition.randomChance(0.35F))))
            .withPool(LootPool.lootPool()
                    // Rare Loot
                    .setRolls(UniformGenerator.between(1, 2))
                    .add(LootItem.lootTableItem(Items.IRON_INGOT)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(2, 8)))
                            .when(LootItemRandomChanceCondition.randomChance(0.75F))
                            .setWeight(110))
                    .add(LootItem.lootTableItem(Items.IRON_INGOT)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(2, 8)))
                            .when(LootItemRandomChanceCondition.randomChance(0.75F))
                            .setWeight(110)))
            .withPool(LootPool.lootPool()
                    // Very Rare Loot
                    .setRolls(UniformGenerator.between(0, 1))
                    .add(LootItem.lootTableItem(Items.IRON_BLOCK)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(0, 2)))
                            .when(LootItemRandomChanceCondition.randomChance(0.35F))
                            .setWeight(25))));

    public static final ResourceLocation CRIMSON_ENT_TREE_LOOT_TABLE = registerTable("chests/ent_tree/crimson_loot",  () -> LootTable.lootTable()
            .withPool(LootPool.lootPool()
                    // Common Loot
                    .setRolls(ConstantValue.exactly(4))
                    .add(LootItem.lootTableItem(Items.CRIMSON_PLANKS)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(8, 14)))
                            .setWeight(70))
                    .add(LootItem.lootTableItem(Items.CRIMSON_PLANKS)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(8, 14)))
                            .setWeight(70))
                    .add(LootItem.lootTableItem(Items.CRIMSON_PLANKS)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(8, 14)))
                            .setWeight(70))
                    .add(LootItem.lootTableItem(Items.CRIMSON_PLANKS)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(8, 14)))
                            .setWeight(70))
                    .add(LootItem.lootTableItem(Items.CRIMSON_STEM)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 5)))
                            .setWeight(100))
                    .add(LootItem.lootTableItem(Items.CRIMSON_STEM)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 5)))
                            .setWeight(100))
                    .add(LootItem.lootTableItem(Items.CRIMSON_STEM)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 5)))
                            .setWeight(100))
                    .add(LootItem.lootTableItem(Items.CRIMSON_STEM)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 5)))
                            .setWeight(100)))
            .withPool(LootPool.lootPool()
                    // Common Loot
                    .setRolls(ConstantValue.exactly(3))
                    .add(LootItem.lootTableItem(Items.CRIMSON_FUNGUS)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 7)))
                            .setWeight(100))
                    .add(LootItem.lootTableItem(Items.CRIMSON_FUNGUS)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5)))
                            .setWeight(50))
                    .add(LootItem.lootTableItem(Items.CRIMSON_ROOTS)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 7)))
                            .setWeight(100))
                    .add(LootItem.lootTableItem(Items.CRIMSON_ROOTS)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5)))
                            .setWeight(50)))
            .withPool(LootPool.lootPool()
                    // Common Loot
                    .setRolls(ConstantValue.exactly(2))
                    .add(LootItem.lootTableItem(Items.CRIMSON_NYLIUM)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5)))
                            .setWeight(25))
                    .add(LootItem.lootTableItem(Items.CRIMSON_NYLIUM)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5)))
                            .setWeight(25))
                    .add(LootItem.lootTableItem(Items.SHROOMLIGHT)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 7)))
                            .setWeight(50))
                    .add(LootItem.lootTableItem(Items.SHROOMLIGHT)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 7)))
                            .setWeight(50)))
            .withPool(LootPool.lootPool()
                    // Rare Loot
                    .setRolls(UniformGenerator.between(0, 2))
                    .add(LootItem.lootTableItem(Items.DIAMOND)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(0, 2)))
                            .when(LootItemRandomChanceCondition.randomChance(0.85F)))
                    .add(LootItem.lootTableItem(Items.GOLD_INGOT)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 4)))
                            .when(LootItemRandomChanceCondition.randomChance(0.95F)))
                    /*.add(LootItem.lootTableItem(CAItems.TIGERS_EYE.get())
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(0, 2)))
                            .when(LootItemRandomChanceCondition.randomChance(0.35F)))*/
                    .add(LootItem.lootTableItem(CAItems.KUNZITE.get())
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(0, 2)))
                            .when(LootItemRandomChanceCondition.randomChance(0.35F))))
            .withPool(LootPool.lootPool()
                    // Very Rare Loot
                    .setRolls(UniformGenerator.between(0, 1))
                    .add(LootItem.lootTableItem(Items.GOLD_BLOCK)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(0, 4)))
                            .when(LootItemRandomChanceCondition.randomChance(0.35F))
                            .setWeight(25)))
            .withPool(LootPool.lootPool()
                    // Very Rare Loot
                    .setRolls(UniformGenerator.between(0, 1))
                    .add(LootItem.lootTableItem(Items.NETHERITE_SCRAP)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5)))
                            .when(LootItemRandomChanceCondition.randomChance(0.25F))
                            .setWeight(25))));

    public static final ResourceLocation DARK_OAK_ENT_TREE_LOOT_TABLE = registerTable("chests/ent_tree/dark_oak_loot",  () -> LootTable.lootTable()
            .withPool(LootPool.lootPool()
                    // Common Loot
                    .setRolls(ConstantValue.exactly(4))
                    .add(LootItem.lootTableItem(Items.DARK_OAK_PLANKS)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(8, 14)))
                            .setWeight(70))
                    .add(LootItem.lootTableItem(Items.DARK_OAK_PLANKS)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(8, 14)))
                            .setWeight(70))
                    .add(LootItem.lootTableItem(Items.DARK_OAK_PLANKS)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(8, 14)))
                            .setWeight(70))
                    .add(LootItem.lootTableItem(Items.DARK_OAK_PLANKS)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(8, 14)))
                            .setWeight(70))
                    .add(LootItem.lootTableItem(Items.DARK_OAK_LOG)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 5)))
                            .setWeight(100))
                    .add(LootItem.lootTableItem(Items.DARK_OAK_LOG)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 5)))
                            .setWeight(100))
                    .add(LootItem.lootTableItem(Items.DARK_OAK_LOG)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 5)))
                            .setWeight(100))
                    .add(LootItem.lootTableItem(Items.DARK_OAK_LOG)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 5)))
                            .setWeight(100)))
            .withPool(LootPool.lootPool()
                    // Common Loot
                    .setRolls(ConstantValue.exactly(3))
                    .add(LootItem.lootTableItem(Items.RED_MUSHROOM)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 7)))
                            .setWeight(100))
                    .add(LootItem.lootTableItem(Items.RED_MUSHROOM)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5)))
                            .setWeight(50))
                    .add(LootItem.lootTableItem(Items.BROWN_MUSHROOM)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 7)))
                            .setWeight(100))
                    .add(LootItem.lootTableItem(Items.BROWN_MUSHROOM)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5)))
                            .setWeight(50))
                    .add(LootItem.lootTableItem(Items.DARK_OAK_LEAVES)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 7)))
                            .setWeight(100))
                    .add(LootItem.lootTableItem(Items.DARK_OAK_LEAVES)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5)))
                            .setWeight(50)))
            .withPool(LootPool.lootPool()
                    // Common Loot
                    .setRolls(ConstantValue.exactly(2))
                    .add(LootItem.lootTableItem(Items.CORNFLOWER)
                            .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1)))
                            .setWeight(30))
                    .add(LootItem.lootTableItem(Items.VINE)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5)))
                            .setWeight(25))
                    .add(LootItem.lootTableItem(Items.VINE)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5)))
                            .setWeight(25))
                    .add(LootItem.lootTableItem(Items.DARK_OAK_SAPLING)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 7)))
                            .setWeight(50))
                    .add(LootItem.lootTableItem(Items.DARK_OAK_SAPLING)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 7)))
                            .setWeight(50)))
            .withPool(LootPool.lootPool()
                    // Rare Loot
                    .setRolls(UniformGenerator.between(0, 2))
                    .add(LootItem.lootTableItem(Items.DIAMOND)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(0, 2)))
                            .when(LootItemRandomChanceCondition.randomChance(0.85F)))
                    .add(LootItem.lootTableItem(Items.EMERALD)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(0, 2)))
                            .when(LootItemRandomChanceCondition.randomChance(0.85F)))
                    /*.add(LootItem.lootTableItem(CAItems.TIGERS_EYE.get())
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(0, 2)))
                            .when(LootItemRandomChanceCondition.randomChance(0.35F)))*/
                    .add(LootItem.lootTableItem(CAItems.KUNZITE.get())
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(0, 2)))
                            .when(LootItemRandomChanceCondition.randomChance(0.35F))))
            .withPool(LootPool.lootPool()
                    // Very Rare Loot
                    .setRolls(UniformGenerator.between(1, 2))
                    .add(LootItem.lootTableItem(Items.DIAMOND)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 2)))
                            .when(LootItemRandomChanceCondition.randomChance(0.75F))
                            .setWeight(25)))
            .withPool(LootPool.lootPool()
                    // Very Rare Loot
                    .setRolls(UniformGenerator.between(1, 2))
                    .add(LootItem.lootTableItem(Items.GOLD_INGOT)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3)))
                            .when(LootItemRandomChanceCondition.randomChance(0.85F))
                            .setWeight(25))));

    public static final ResourceLocation GINKGO_ENT_TREE_LOOT_TABLE = registerTable("chests/ent_tree/ginkgo_loot",  () -> LootTable.lootTable()
            .withPool(LootPool.lootPool()
                    // Common Loot
                    .setRolls(ConstantValue.exactly(4))
                    .add(LootItem.lootTableItem(CABlocks.GINKGO_PLANKS.get())
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(8, 14))).setWeight(70))
                    .add(LootItem.lootTableItem(CABlocks.GINKGO_PLANKS.get())
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(8, 14))).setWeight(70))
                    .add(LootItem.lootTableItem(CABlocks.GINKGO_PLANKS.get())
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(8, 14))).setWeight(70))
                    .add(LootItem.lootTableItem(CABlocks.GINKGO_PLANKS.get())
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(8, 14))).setWeight(70))
                    .add(LootItem.lootTableItem(CABlocks.GINKGO_PLANKS.get())
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 5))).setWeight(100))
                    .add(LootItem.lootTableItem(CABlocks.GINKGO_PLANKS.get())
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 5))).setWeight(100))
                    .add(LootItem.lootTableItem(CABlocks.GINKGO_PLANKS.get())
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 5))).setWeight(100))
                    .add(LootItem.lootTableItem(CABlocks.GINKGO_PLANKS.get())
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 5))).setWeight(100)))
            .withPool(LootPool.lootPool()
                    // Common Loot
                    .setRolls(ConstantValue.exactly(3))
                    .add(LootItem.lootTableItem(CABlocks.GINKGO_LEAVES.get())
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 7))).setWeight(100))
                    .add(LootItem.lootTableItem(CABlocks.GINKGO_LEAVES.get())
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5))).setWeight(50))
                    .add(LootItem.lootTableItem(CABlocks.DENSE_DIRT.get())
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 7))).setWeight(100))
                    .add(LootItem.lootTableItem(CABlocks.DENSE_DIRT.get())
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5))).setWeight(50)))
            .withPool(LootPool.lootPool()
                    // Common Loot
                    .setRolls(ConstantValue.exactly(2))
                    .add(LootItem.lootTableItem(CABlocks.BLUE_BULB.get())
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5))).setWeight(25))
                    .add(LootItem.lootTableItem(CABlocks.BLUE_BULB.get())
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5))).setWeight(25))
                    .add(LootItem.lootTableItem(CABlocks.PINK_BULB.get())
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5))).setWeight(25))
                    .add(LootItem.lootTableItem(CABlocks.PINK_BULB.get())
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5))).setWeight(25))
                    .add(LootItem.lootTableItem(CABlocks.PURPLE_BULB.get())
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5))).setWeight(25))
                    .add(LootItem.lootTableItem(CABlocks.PURPLE_BULB.get())
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5))).setWeight(25))
                    .add(LootItem.lootTableItem(CABlocks.GINKGO_SAPLING.get())
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 7))).setWeight(50))
                    .add(LootItem.lootTableItem(CABlocks.GINKGO_SAPLING.get())
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 7))).setWeight(50)))
            .withPool(LootPool.lootPool()
                    // Rare Loot
                    .setRolls(UniformGenerator.between(0, 1))
                    .add(LootItem.lootTableItem(Items.DIAMOND)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(0, 2)))
                            .when(LootItemRandomChanceCondition.randomChance(0.85F)))
                    .add(LootItem.lootTableItem(Items.EMERALD)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(0, 2)))
                            .when(LootItemRandomChanceCondition.randomChance(0.85F)))
                    /*.add(LootItem.lootTableItem(CAItems.TIGERS_EYE.get())
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(0, 2)))
                            .when(LootItemRandomChanceCondition.randomChance(0.35F)))*/
                    .add(LootItem.lootTableItem(CAItems.KUNZITE.get())
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(0, 2)))
                            .when(LootItemRandomChanceCondition.randomChance(0.35F)))));

    public static final ResourceLocation JUNGLE_ENT_TREE_LOOT_TABLE = registerTable("chests/ent_tree/jungle_loot",  () -> LootTable.lootTable()
            .withPool(LootPool.lootPool()
                    // Common Loot
                    .setRolls(ConstantValue.exactly(4))
                    .add(LootItem.lootTableItem(Items.JUNGLE_PLANKS)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(8, 14)))
                            .setWeight(70))
                    .add(LootItem.lootTableItem(Items.JUNGLE_PLANKS)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(8, 14)))
                            .setWeight(70))
                    .add(LootItem.lootTableItem(Items.JUNGLE_PLANKS)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(8, 14)))
                            .setWeight(70))
                    .add(LootItem.lootTableItem(Items.JUNGLE_PLANKS)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(8, 14)))
                            .setWeight(70))
                    .add(LootItem.lootTableItem(Items.JUNGLE_LOG)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 5)))
                            .setWeight(100))
                    .add(LootItem.lootTableItem(Items.JUNGLE_LOG)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 5)))
                            .setWeight(100))
                    .add(LootItem.lootTableItem(Items.JUNGLE_LOG)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 5)))
                            .setWeight(100))
                    .add(LootItem.lootTableItem(Items.JUNGLE_LOG)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 5)))
                            .setWeight(100)))
            .withPool(LootPool.lootPool()
                    // Common Loot
                    .setRolls(ConstantValue.exactly(3))
                    .add(LootItem.lootTableItem(Items.JUNGLE_LEAVES)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 7)))
                            .setWeight(100))
                    .add(LootItem.lootTableItem(Items.JUNGLE_LEAVES)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5)))
                            .setWeight(50))
                    .add(LootItem.lootTableItem(Items.VINE)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 7)))
                            .setWeight(100))
                    .add(LootItem.lootTableItem(Items.VINE)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5)))
                            .setWeight(50))
                    .add(LootItem.lootTableItem(Items.COCOA_BEANS)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 7)))
                            .setWeight(100))
                    .add(LootItem.lootTableItem(Items.COCOA_BEANS)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5)))
                            .setWeight(50)))
            .withPool(LootPool.lootPool()
                    // Common Loot
                    .setRolls(ConstantValue.exactly(2))
                    .add(LootItem.lootTableItem(Items.BAMBOO)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5)))
                            .setWeight(25))
                    .add(LootItem.lootTableItem(Items.BAMBOO)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5)))
                            .setWeight(25))
                    .add(LootItem.lootTableItem(Items.JUNGLE_SAPLING)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 7)))
                            .setWeight(50))
                    .add(LootItem.lootTableItem(Items.JUNGLE_SAPLING)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 7)))
                            .setWeight(50)))
            .withPool(LootPool.lootPool()
                    // Common Loot
                    .setRolls(ConstantValue.exactly(2))
                    .add(LootItem.lootTableItem(Items.MELON_SEEDS)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5)))
                            .setWeight(50))
                    .add(LootItem.lootTableItem(Items.MELON_SEEDS)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5)))
                            .setWeight(50))
                    .add(LootItem.lootTableItem(Items.MELON_SLICE)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 7)))
                            .setWeight(75))
                    .add(LootItem.lootTableItem(Items.MELON_SLICE)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 7)))
                            .setWeight(75))
                    .add(LootItem.lootTableItem(Items.MELON)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3)))
                            .setWeight(25))
                    .add(LootItem.lootTableItem(Items.MELON)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3)))
                            .setWeight(25)))
            .withPool(LootPool.lootPool()
                    // Rare Loot
                    .setRolls(UniformGenerator.between(0, 2))
                    .add(LootItem.lootTableItem(Items.DIAMOND)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(0, 2)))
                            .when(LootItemRandomChanceCondition.randomChance(0.85F)))
                    .add(LootItem.lootTableItem(Items.EMERALD)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(0, 2)))
                            .when(LootItemRandomChanceCondition.randomChance(0.85F)))
                    /*.add(LootItem.lootTableItem(CAItems.TIGERS_EYE.get())
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(0, 2)))
                            .when(LootItemRandomChanceCondition.randomChance(0.35F)))*/
                    .add(LootItem.lootTableItem(CAItems.KUNZITE.get())
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(0, 2)))
                            .when(LootItemRandomChanceCondition.randomChance(0.35F))))
            .withPool(LootPool.lootPool()
                    // Very Rare Loot
                    .setRolls(ConstantValue.exactly(3))
                    .add(LootItem.lootTableItem(Items.DIAMOND)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 2)))
                            .setWeight(130))
                    .add(LootItem.lootTableItem(Items.EMERALD)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 2)))
                            .setWeight(130))
                    /*.add(LootItem.lootTableItem(CAItems.TIGERS_EYE.get())
                            .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1)))
                            .setWeight(70))*/
                    .add(LootItem.lootTableItem(CAItems.KUNZITE.get())
                            .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1)))
                            .setWeight(70))
                    .add(LootItem.lootTableItem(CAItems.RUBY.get())
                            .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1)))
                            .when(LootItemRandomChanceCondition.randomChance(0.35F))
                            .setWeight(35))
                    /*.add(LootItem.lootTableItem(CAItems.PLATINUM_LUMP.get())
                            .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1)))
                            .when(LootItemRandomChanceCondition.randomChance(0.35F))
                            .setWeight(35))*/
                    .add(LootItem.lootTableItem(CAItems.TITANIUM_NUGGET.get())
                            .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1)))
                            .when(LootItemRandomChanceCondition.randomChance(0.15F))
                            .setWeight(5))
                    .add(LootItem.lootTableItem(CAItems.URANIUM_NUGGET.get())
                            .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1)))
                            .when(LootItemRandomChanceCondition.randomChance(0.15F))
                            .setWeight(5))));

    public static final ResourceLocation JUNGLE_ENT_TREE_TRAP_LOOT_TABLE = registerTable("chests/ent_tree/jungle_trap_loot",  () -> LootTable.lootTable()
            .withPool(LootPool.lootPool()
                    // Common Loot
                    .setRolls(ConstantValue.exactly(4))
                    .add(LootItem.lootTableItem(Items.TIPPED_ARROW)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(4.0F, 9.0F)))
                            .apply(SetNbtFunction.setTag(
                                    Util.make(new CompoundTag(), (nbt) -> nbt.putString("Potion", "minecraft:poison")))))
                    .add(LootItem.lootTableItem(Items.TIPPED_ARROW)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(2.0F, 6.0F)))
                            .apply(SetNbtFunction.setTag(Util.make(new CompoundTag(),
                                    (nbt) -> nbt.putString("Potion", "minecraft:long_poison")))))
                    .add(LootItem.lootTableItem(Items.TIPPED_ARROW)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1.0F, 4.0F)))
                            .apply(SetNbtFunction.setTag(Util.make(new CompoundTag(),
                                    (nbt) -> nbt.putString("Potion", "minecraft:strong_poison")))))));

    public static final ResourceLocation OAK_ENT_TREE_LOOT_TABLE = registerTable("chests/ent_tree/oak_loot",  () -> LootTable.lootTable()
            .withPool(LootPool.lootPool()
                    // Common Loot
                    .setRolls(ConstantValue.exactly(4))
                    .add(LootItem.lootTableItem(Items.OAK_PLANKS)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(8, 14)))
                            .setWeight(70))
                    .add(LootItem.lootTableItem(Items.OAK_PLANKS)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(8, 14)))
                            .setWeight(70))
                    .add(LootItem.lootTableItem(Items.OAK_PLANKS)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(8, 14)))
                            .setWeight(70))
                    .add(LootItem.lootTableItem(Items.OAK_PLANKS)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(8, 14)))
                            .setWeight(70))
                    .add(LootItem.lootTableItem(Items.OAK_LOG)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 5)))
                            .setWeight(100))
                    .add(LootItem.lootTableItem(Items.OAK_LOG)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 5)))
                            .setWeight(100))
                    .add(LootItem.lootTableItem(Items.OAK_LOG)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 5)))
                            .setWeight(100))
                    .add(LootItem.lootTableItem(Items.OAK_LOG)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 5)))
                            .setWeight(100)))
            .withPool(LootPool.lootPool()
                    // Common Loot
                    .setRolls(ConstantValue.exactly(3))
                    .add(LootItem.lootTableItem(Items.RED_MUSHROOM)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 7)))
                            .setWeight(100))
                    .add(LootItem.lootTableItem(Items.RED_MUSHROOM)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5)))
                            .setWeight(50))
                    .add(LootItem.lootTableItem(Items.BROWN_MUSHROOM)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 7)))
                            .setWeight(100))
                    .add(LootItem.lootTableItem(Items.BROWN_MUSHROOM)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5)))
                            .setWeight(50))
                    .add(LootItem.lootTableItem(Items.OAK_LEAVES)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 7)))
                            .setWeight(100))
                    .add(LootItem.lootTableItem(Items.OAK_LEAVES)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5)))
                            .setWeight(50)))
            .withPool(LootPool.lootPool()
                    // Common Loot
                    .setRolls(ConstantValue.exactly(2))
                    .add(LootItem.lootTableItem(Items.RED_MUSHROOM)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5)))
                            .setWeight(50))
                    .add(LootItem.lootTableItem(Items.BROWN_MUSHROOM)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5)))
                            .setWeight(50))
                    .add(LootItem.lootTableItem(Items.OAK_SAPLING)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 7)))
                            .setWeight(50))
                    .add(LootItem.lootTableItem(Items.OAK_SAPLING)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 7)))
                            .setWeight(50)))
            .withPool(LootPool.lootPool()
                    // Rare Loot
                    .setRolls(UniformGenerator.between(0, 2))
                    .add(LootItem.lootTableItem(Items.DIAMOND)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(0, 2)))
                            .when(LootItemRandomChanceCondition.randomChance(0.85F)))
                    .add(LootItem.lootTableItem(Items.EMERALD)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(0, 2)))
                            .when(LootItemRandomChanceCondition.randomChance(0.85F)))
                    /*.add(LootItem.lootTableItem(CAItems.TIGERS_EYE.get())
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(0, 2)))
                            .when(LootItemRandomChanceCondition.randomChance(0.35F)))*/
                    .add(LootItem.lootTableItem(CAItems.KUNZITE.get())
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(0, 2)))
                            .when(LootItemRandomChanceCondition.randomChance(0.35F))))
            .withPool(LootPool.lootPool()
                    // Rare Loot
                    .setRolls(UniformGenerator.between(0, 2))
                    .add(LootItem.lootTableItem(Items.IRON_INGOT)
                            .when(LootItemRandomChanceCondition.randomChance(0.35F)))
                    .add(LootItem.lootTableItem(Items.GOLDEN_APPLE)
                            .when(LootItemRandomChanceCondition.randomChance(0.25F)))
                    .add(LootItem.lootTableItem(Items.ENCHANTED_GOLDEN_APPLE)
                            .when(LootItemRandomChanceCondition.randomChance(0.025F))))
            /*.withPool(LootPool.lootPool()
                    // Rare Loot
                    .setRolls(UniformGenerator.between(0, 1))
                    .add(LootItem.lootTableItem(CABlocks.APPLE_SAPLING.get().asItem())
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(0, 2)))
                            .setWeight(150)))*/);

    public static final ResourceLocation SPRUCE_ENT_TREE_LOOT_TABLE = registerTable("chests/ent_tree/spruce_loot",  () -> LootTable.lootTable()
            .withPool(LootPool.lootPool()
                    // Common Loot
                    .setRolls(ConstantValue.exactly(4))
                    .add(LootItem.lootTableItem(Items.SPRUCE_PLANKS)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(8, 14)))
                            .setWeight(70))
                    .add(LootItem.lootTableItem(Items.SPRUCE_PLANKS)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(8, 14)))
                            .setWeight(70))
                    .add(LootItem.lootTableItem(Items.SPRUCE_PLANKS)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(8, 14)))
                            .setWeight(70))
                    .add(LootItem.lootTableItem(Items.SPRUCE_PLANKS)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(8, 14)))
                            .setWeight(70))
                    .add(LootItem.lootTableItem(Items.SPRUCE_LOG)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 5)))
                            .setWeight(100))
                    .add(LootItem.lootTableItem(Items.SPRUCE_LOG)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 5)))
                            .setWeight(100))
                    .add(LootItem.lootTableItem(Items.SPRUCE_LOG)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 5)))
                            .setWeight(100))
                    .add(LootItem.lootTableItem(Items.SPRUCE_LOG)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 5)))
                            .setWeight(100)))
            .withPool(LootPool.lootPool()
                    // Common Loot
                    .setRolls(ConstantValue.exactly(3))
                    .add(LootItem.lootTableItem(Items.SPRUCE_LEAVES)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 7)))
                            .setWeight(100))
                    .add(LootItem.lootTableItem(Items.SPRUCE_LEAVES)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5)))
                            .setWeight(50))
                    .add(LootItem.lootTableItem(Items.PODZOL)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 7)))
                            .setWeight(100))
                    .add(LootItem.lootTableItem(Items.PODZOL)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5)))
                            .setWeight(50))
                    .add(LootItem.lootTableItem(Items.COARSE_DIRT)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 7)))
                            .setWeight(100))
                    .add(LootItem.lootTableItem(Items.COARSE_DIRT)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5)))
                            .setWeight(50)))
            .withPool(LootPool.lootPool()
                    // Common Loot
                    .setRolls(ConstantValue.exactly(3))
                    .add(LootItem.lootTableItem(Items.SPRUCE_LEAVES)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 7)))
                            .setWeight(100))
                    .add(LootItem.lootTableItem(Items.SPRUCE_LEAVES)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5)))
                            .setWeight(50))
                    .add(LootItem.lootTableItem(Items.MOSSY_COBBLESTONE)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 7)))
                            .setWeight(100))
                    .add(LootItem.lootTableItem(Items.MOSSY_COBBLESTONE)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5)))
                            .setWeight(50))
                    .add(LootItem.lootTableItem(Items.COARSE_DIRT)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 7)))
                            .setWeight(100))
                    .add(LootItem.lootTableItem(Items.COARSE_DIRT)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5)))
                            .setWeight(50)))
            .withPool(LootPool.lootPool()
                    // Common Loot
                    .setRolls(ConstantValue.exactly(2))
                    .add(LootItem.lootTableItem(Items.FERN)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5)))
                            .setWeight(25))
                    .add(LootItem.lootTableItem(Items.FERN)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5)))
                            .setWeight(25))
                    .add(LootItem.lootTableItem(Items.SPRUCE_SAPLING)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 7)))
                            .setWeight(50))
                    .add(LootItem.lootTableItem(Items.SPRUCE_SAPLING)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 7)))
                            .setWeight(50)))
            .withPool(LootPool.lootPool()
                    // Rare Loot
                    .setRolls(UniformGenerator.between(0, 2))
                    .add(LootItem.lootTableItem(Items.DIAMOND)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(0, 2)))
                            .when(LootItemRandomChanceCondition.randomChance(0.85F)))
                    .add(LootItem.lootTableItem(Items.EMERALD)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(0, 2)))
                            .when(LootItemRandomChanceCondition.randomChance(0.85F)))
                    /*.add(LootItem.lootTableItem(CAItems.TIGERS_EYE.get())
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(0, 2)))
                            .when(LootItemRandomChanceCondition.randomChance(0.35F)))*/
                    .add(LootItem.lootTableItem(CAItems.KUNZITE.get())
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(0, 2)))
                            .when(LootItemRandomChanceCondition.randomChance(0.35F))))
            /*.withPool(LootPool.lootPool()
                    // Rare Loot
                    .setRolls(UniformGenerator.between(1, 2))
                    .add(LootItem.lootTableItem(CAItems.TIGERS_EYE.get())
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3)))
                            .when(LootItemRandomChanceCondition.randomChance(0.85F))))*/);

    public static final ResourceLocation WARPED_ENT_TREE_LOOT_TABLE = registerTable("chests/ent_tree/warped_loot",  () -> LootTable.lootTable()
            .withPool(LootPool.lootPool()
                    // Common Loot
                    .setRolls(ConstantValue.exactly(4))
                    .add(LootItem.lootTableItem(Items.WARPED_PLANKS)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(8, 14)))
                            .setWeight(70))
                    .add(LootItem.lootTableItem(Items.WARPED_PLANKS)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(8, 14)))
                            .setWeight(70))
                    .add(LootItem.lootTableItem(Items.WARPED_PLANKS)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(8, 14)))
                            .setWeight(70))
                    .add(LootItem.lootTableItem(Items.WARPED_PLANKS)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(8, 14)))
                            .setWeight(70))
                    .add(LootItem.lootTableItem(Items.WARPED_STEM)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 5)))
                            .setWeight(100))
                    .add(LootItem.lootTableItem(Items.WARPED_STEM)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 5)))
                            .setWeight(100))
                    .add(LootItem.lootTableItem(Items.WARPED_STEM)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 5)))
                            .setWeight(100))
                    .add(LootItem.lootTableItem(Items.WARPED_STEM)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 5)))
                            .setWeight(100)))
            .withPool(LootPool.lootPool()
                    // Common Loot
                    .setRolls(ConstantValue.exactly(3))
                    .add(LootItem.lootTableItem(Items.WARPED_FUNGUS)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 7)))
                            .setWeight(100))
                    .add(LootItem.lootTableItem(Items.WARPED_FUNGUS)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5)))
                            .setWeight(50))
                    .add(LootItem.lootTableItem(Items.WARPED_ROOTS)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 7)))
                            .setWeight(100))
                    .add(LootItem.lootTableItem(Items.WARPED_ROOTS)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5)))
                            .setWeight(50)))
            .withPool(LootPool.lootPool()
                    // Common Loot
                    .setRolls(ConstantValue.exactly(2))
                    .add(LootItem.lootTableItem(Items.WARPED_NYLIUM)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5)))
                            .setWeight(25))
                    .add(LootItem.lootTableItem(Items.WARPED_NYLIUM)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5)))
                            .setWeight(25))
                    .add(LootItem.lootTableItem(Items.SHROOMLIGHT)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 7)))
                            .setWeight(50))
                    .add(LootItem.lootTableItem(Items.SHROOMLIGHT)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 7)))
                            .setWeight(50)))
            .withPool(LootPool.lootPool()
                    // Rare Loot
                    .setRolls(UniformGenerator.between(0, 2))
                    .add(LootItem.lootTableItem(Items.DIAMOND)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(0, 2)))
                            .when(LootItemRandomChanceCondition.randomChance(0.85F)))
                    .add(LootItem.lootTableItem(Items.GOLD_INGOT)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 4)))
                            .when(LootItemRandomChanceCondition.randomChance(0.95F)))
                    /*.add(LootItem.lootTableItem(CAItems.TIGERS_EYE.get())
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(0, 2)))
                            .when(LootItemRandomChanceCondition.randomChance(0.35F)))*/
                    .add(LootItem.lootTableItem(CAItems.KUNZITE.get())
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(0, 2)))
                            .when(LootItemRandomChanceCondition.randomChance(0.35F))))
            .withPool(LootPool.lootPool()
                    // Very Rare Loot
                    .setRolls(UniformGenerator.between(0, 1))
                    .add(LootItem.lootTableItem(Items.GOLD_BLOCK)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(0, 4)))
                            .when(LootItemRandomChanceCondition.randomChance(0.35F))
                            .setWeight(25)))
            .withPool(LootPool.lootPool()
                    // Very Rare Loot
                    .setRolls(UniformGenerator.between(0, 1))
                    .add(LootItem.lootTableItem(Items.NETHERITE_SCRAP)
                            .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5)))
                            .when(LootItemRandomChanceCondition.randomChance(0.25F))
                            .setWeight(25))));

    private static ResourceLocation registerTable(String id, Supplier<LootTable.Builder> tableSupplier) {
        ResourceLocation tableLocation = new ResourceLocation(CAConstants.MODID, id);
        LOOT_TABLES.add(Pair.of(tableLocation, tableSupplier));
        return tableLocation;
    }
}
